### ISSUE TITLE
Blank measurement

### ISSUE THREAD

**Issue by NicholasSloan** [mekkablue/ShowDistanceBetweenTwoPoints#1]
Hi Rainer, are you still supporting this reporter plugin? I seem to be getting a blank grey measurement field (Glyphs 965, Mac OS 10.11.6). Screenshot below.
I have tried removing and reloading a fresh copy.
Thanks, Nick
![showdistance screenshot 23-1-17](https://cloud.githubusercontent.com/assets/20109637/22206033/62910b0c-e171-11e6-893c-f339c55ee4f3.png)

**Comment by mekkablue** [comment]
This is a problem in the current API of Glyphs. You will have to wait for the next app update, I am afraid.

**Comment by NicholasSloan** [comment]
Thanks Rainer.

**Comment by mekkablue** [comment]
I uploaded a temporary fix for 965 (which has its problems if you scale in very far).
