### ISSUE TITLE
Not working in recent versions of Glyphs?

### ISSUE THREAD

**Issue by NicholasSloan** [mekkablue/ShowDistanceBetweenTwoPoints#2]
Hi, I have come back to Glyphs after a period away, and this plugin which worked perfectly before no longer seems to do anything at all. I have migrated all my plugins (where possible) to Plugin Manager installs, so using v 1.0.3 in Glyphs 2.5.2 (build 1140).
Thanks, Nick

**Comment by mekkablue** [comment]
Fixed it, thanks for reporting.
